### ISSUE TITLE
Port to generics-sop-0.3.2.0

### ISSUE THREAD

**Issue by Mikolaj** [openbrainsrc/postgresql-simple-sop#6]
No idea how hard that could be.

**Comment by Mikolaj** [comment]
The current dep is a problem, because generics-sop-0.2.5.0 implies template-haskell-2.12.0.0, which is older than what comes even with GHC 8.4.4 and using an old  template-haskell is risky.

**Comment by Mikolaj** [comment]
@kosmikus suspects the current codebase would work fine with generics-sop-0.4.0.1, so it's just the matter of publishing to Hackage. May I help?

**Comment by Mikolaj** [comment]
@openbrainsrc: ping?

**Comment by adamgundry** [comment]
It appears the `postgresql-simple-sop-0.2` release builds against `generics-sop-0.4.0.1` if the bounds are overridden, but does not build with `generics-sop-0.5.0.0` due to a breaking change:
```
src/Database/PostgreSQL/Simple/SOP.hs:71:5: error:
        • The constructor ‘ADT’ should have 4 arguments, but has been given 3
        • In the pattern: ADT _ _ cs
          In a case alternative: ADT _ _ cs -> fNms cs
          In the expression:
            case datatypeInfo p of
              ADT _ _ cs -> fNms cs
              Newtype _ _ c -> fNms $ c :* Nil
       |
    71 |     ADT     _ _ cs -> fNms cs
       |     ^^^^^^^^^^^^^^
```
